config/routes.rb
Intranet::Application.routes.draw do
  resources :produits

  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :factures do
    resources :facture_items
  end
  
  resources :facture_items

  resources :clients

  resources :types

  resources :statuts

  resources :tvas

  resources :users

  get 'home' => "home#index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :adresse_pays, :adresse_cp, :adresse_numero, :adresse_rue, :adresse_ville, :mail, :mobile, :societe, :numero_tva, :telephone
  
  has_many :factures
  
  def adresse_complete
    "#{self.adresse_numero} #{self.adresse_rue} #{self.adresse_cp} #{self.adresse_ville} #{self.adresse_pays}"
  end
end

app/models/facture.rb
class Facture < ActiveRecord::Base
  attr_accessible :date_facturation, :delai_paiement, :intitule, :reference, :statut_id, :type_id, :client_id, :user_id
  
  belongs_to :user
  belongs_to :client
  belongs_to :type
  belongs_to :statut
  
  has_many :facture_items
  has_many :produits, :through => :facture_items
  
  def total_htva
    facture_items.to_a.sum { |facture_item| facture_item.total_htva }
  end
  
  def total_tva
    facture_items.to_a.sum { |facture_item| facture_item.total_tva }
  end
  
  def produits_list
    produits.map { |p| p.nom }.join(", ")
  end
end

app/models/facture_item.rb
class FactureItem < ActiveRecord::Base
  attr_accessible :descritpion, :libelle, :prix, :quantite, :tva_id, :produit_id
  
  belongs_to :facture
  belongs_to :produit
  belongs_to :tva
  
  def total_htva
    prix * quantite
  end
  
  def total_tva
    tva_value = Tva.find(tva_id)
    tva_taux = 1.0 + (tva_value.value.to_f / 100)
    total_htva * tva_taux
  end
end

app/models/produit.rb
class Produit < ActiveRecord::Base
  attr_accessible :nom, :quantite, :reference, :prix
  
  has_many :facture_items
  has_many :factures, :through => :facture_items
end

app/models/statut.rb
class Statut < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/tva.rb
class Tva < ActiveRecord::Base
  attr_accessible :display, :libelle, :value
  
  has_many :facture_item
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :login, :mail, :hashed_password, :salt, :password_confirmation, :password
  has_many :factures
  
  validates :login, :presence => true, :uniqueness => true
  
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  
  validate :password_must_be_present
  
  after_destroy :ensure_an_user_remains 
  
  def User.authenticate(login, password)
    if user = find_by_login(login)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "security" + salt)
  end
  
  # 'password' = attribut virtuel
  def password=(password)
    @password = password
   
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private
    def password_must_be_present
      errors.add(:password, 'Missing password') unless hashed_password.present?
    end
  
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def ensure_an_user_remains
    if User.count.zero?
      raise "Can't delete last user!"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_factures = Facture.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize
  
  def index
  end
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  # GET /produits
  # GET /produits.json
  def index
    @produits = Produit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produits }
    end
  end

  # GET /produits/1
  # GET /produits/1.json
  def show
    @produit = Produit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/new
  # GET /produits/new.json
  def new
    @produit = Produit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/1/edit
  def edit
    @produit = Produit.find(params[:id])
  end

  # POST /produits
  # POST /produits.json
  def create
    @produit = Produit.new(params[:produit])

    respond_to do |format|
      if @produit.save
        format.html { redirect_to @produit, notice: 'Produit was successfully created.' }
        format.json { render json: @produit, status: :created, location: @produit }
      else
        format.html { render action: "new" }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produits/1
  # PUT /produits/1.json
  def update
    @produit = Produit.find(params[:id])

    respond_to do |format|
      if @produit.update_attributes(params[:produit])
        format.html { redirect_to @produit, notice: 'Produit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1
  # DELETE /produits/1.json
  def destroy
    @produit = Produit.find(params[:id])
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to produits_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tvas_controller.rb
class TvasController < ApplicationController
  # GET /tvas
  # GET /tvas.json
  def index
    @tvas = Tva.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tvas }
    end
  end

  # GET /tvas/1
  # GET /tvas/1.json
  def show
    @tva = Tva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tva }
    end
  end

  # GET /tvas/new
  # GET /tvas/new.json
  def new
    @tva = Tva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tva }
    end
  end

  # GET /tvas/1/edit
  def edit
    @tva = Tva.find(params[:id])
  end

  # POST /tvas
  # POST /tvas.json
  def create
    @tva = Tva.new(params[:tva])

    respond_to do |format|
      if @tva.save
        format.html { redirect_to @tva, notice: 'Tva was successfully created.' }
        format.json { render json: @tva, status: :created, location: @tva }
      else
        format.html { render action: "new" }
        format.json { render json: @tva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tvas/1
  # PUT /tvas/1.json
  def update
    @tva = Tva.find(params[:id])

    respond_to do |format|
      if @tva.update_attributes(params[:tva])
        format.html { redirect_to @tva, notice: 'Tva was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tvas/1
  # DELETE /tvas/1.json
  def destroy
    @tva = Tva.find(params[:id])
    @tva.destroy

    respond_to do |format|
      format.html { redirect_to tvas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuts_helper.rb
module StatutsHelper
end

app/helpers/tvas_helper.rb
module TvasHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/produits/_form.html.erb
<%= form_for(@produit) do |f| %>
  <% if @produit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
      <% @produit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prix %><br />
    <%= f.text_field :prix %>
  </div>
  <div class="field">
    <%= f.label :quantite %><br />
    <%= f.number_field :quantite, :min => 0, :max => 9999, :value => 1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produits/edit.html.erb
<h1>Editing produit</h1>

<%= render 'form' %>

<%= link_to 'Show', @produit %> |
<%= link_to 'Back', produits_path %>

app/views/produits/index.html.erb
<h1>Listing produits</h1>

<table>
  <tr>
    <th>Reference</th>
    <th>Nom</th>
    <th>Quantite</th>
    <th>Facture item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produits.each do |produit| %>
  <tr>
    <td><%= produit.reference %></td>
    <td><%= produit.nom %></td>
    <td><%= produit.quantite %></td>
    <td><%= number_to_currency(produit.prix, :unit => "€") %></td>
    <td><%= link_to 'Show', produit %></td>
    <td><%= link_to 'Edit', edit_produit_path(produit) %></td>
    <td><%= link_to 'Destroy', produit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produit', new_produit_path %>

app/views/produits/new.html.erb
<h1>New produit</h1>

<%= render 'form' %>

<%= link_to 'Back', produits_path %>

app/views/produits/show.html.erb
<p>
  <b>Reference:</b>
  <%= @produit.reference %>
</p>

<p>
  <b>Nom:</b>
  <%= @produit.nom %>
</p>

<p>
  <b>Prix:</b>
  <%= number_to_currency(@produit.prix, :unit => "€") %>
</p>

<p>
  <b>Quantite:</b>
  <%= @produit.quantite %>
</p>


<%= link_to 'Edit', edit_produit_path(@produit) %> |
<%= link_to 'Back', produits_path %>