config/routes.rb
Intranet::Application.routes.draw do
  resources :produits

  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :factures do
    resources :facture_items
  end
  
  resources :facture_items

  resources :clients

  resources :types

  resources :statuts

  resources :tvas

  resources :users

  get 'home' => "home#index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :adresse_pays, :adresse_cp, :adresse_numero, :adresse_rue, :adresse_ville, :mail, :mobile, :societe, :numero_tva, :telephone
  
  has_many :factures
  
  def adresse_complete
    "#{self.adresse_numero} #{self.adresse_rue} #{self.adresse_cp} #{self.adresse_ville} #{self.adresse_pays}"
  end
end

app/models/facture.rb
class Facture < ActiveRecord::Base
  attr_accessible :date_facturation, :delai_paiement, :intitule, :reference, :statut_id, :type_id, :client_id, :user_id
  
  belongs_to :user
  belongs_to :client
  belongs_to :type
  belongs_to :statut
  
  has_many :facture_items
  has_many :produits, :through => :facture_items
  
  def total_htva
    facture_items.to_a.sum { |facture_item| facture_item.total_htva }
  end
  
  def total_tva
    facture_items.to_a.sum { |facture_item| facture_item.total_tva }
  end
  
  def produits_list
    produits.map { |p| p.nom }.join(", ")
  end
end

app/models/facture_item.rb
class FactureItem < ActiveRecord::Base
  attr_accessible :descritpion, :libelle, :prix, :quantite, :tva_id, :produit_id
  
  belongs_to :facture
  belongs_to :produit
  belongs_to :tva
  
  def total_htva
    prix * quantite
  end
  
  def total_tva
    tva_value = Tva.find(tva_id)
    tva_taux = 1.0 + (tva_value.value.to_f / 100)
    total_htva * tva_taux
  end
end

app/models/produit.rb
class Produit < ActiveRecord::Base
  attr_accessible :nom, :quantite, :reference, :prix
  
  has_many :facture_items
  has_many :factures, :through => :facture_items
end

app/models/statut.rb
class Statut < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/tva.rb
class Tva < ActiveRecord::Base
  attr_accessible :display, :libelle, :value
  
  has_many :facture_item
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :login, :mail, :hashed_password, :salt, :password_confirmation, :password
  has_many :factures
  
  validates :login, :presence => true, :uniqueness => true
  
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  
  validate :password_must_be_present
  
  after_destroy :ensure_an_user_remains 
  
  def User.authenticate(login, password)
    if user = find_by_login(login)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "security" + salt)
  end
  
  # 'password' = attribut virtuel
  def password=(password)
    @password = password
   
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private
    def password_must_be_present
      errors.add(:password, 'Missing password') unless hashed_password.present?
    end
  
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def ensure_an_user_remains
    if User.count.zero?
      raise "Can't delete last user!"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize
  
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuts_helper.rb
module StatutsHelper
end

app/helpers/tvas_helper.rb
module TvasHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
It's <%= Time.now %><br />
We have <%= pluralize(@total_factures, "facture") %>.

app/views/shared/_footer.html.erb
aurevec.be

app/views/shared/_header.html.erb
<h1>RoR Intranet application for demo</h1> 

app/views/shared/_login.html.erb
<%= form_tag '/login' do %>
	<fieldset>
		<legend>Log In</legend>
		
		<div>
			<label for="name">Login:</label>
			<%= text_field_tag :login, params[:login] %>
		</div>
		
		<div>
			<label for="password">Password:</label>
			<%= password_field_tag :password, params[:password] %>
		</div>
		
		<div>
			<%= submit_tag "Login" %>
		</div>
	</fieldset>
<% end %>

app/views/shared/_menu.html.erb
<h1>Menu</h1><br />
<% if session[:user_id] %>
<%= link_to "User", users_path %><br />
<%= link_to "TVA", tvas_path %><br />
<%= link_to "Statut", statuts_path %><br />
<%= link_to "Type", types_path %><br />
<%= link_to "Client", clients_path %><br />
<%= link_to "Facture", factures_path %><br />
<%= link_to "Produit", produits_path %><br />
<br /><%= button_to "Logout", logout_path, :method => :delete %>
<% else %>
<p>You must be logged in.</p>
<% end %>