config/routes.rb
Intranet::Application.routes.draw do
  resources :produits

  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :factures do
    resources :facture_items
  end
  
  resources :facture_items

  resources :clients

  resources :types

  resources :statuts

  resources :tvas

  resources :users

  get 'home' => "home#index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :adresse_pays, :adresse_cp, :adresse_numero, :adresse_rue, :adresse_ville, :mail, :mobile, :societe, :numero_tva, :telephone
  
  has_many :factures
  
  def adresse_complete
    "#{self.adresse_numero} #{self.adresse_rue} #{self.adresse_cp} #{self.adresse_ville} #{self.adresse_pays}"
  end
end

app/models/facture.rb
class Facture < ActiveRecord::Base
  attr_accessible :date_facturation, :delai_paiement, :intitule, :reference, :statut_id, :type_id, :client_id, :user_id
  
  belongs_to :user
  belongs_to :client
  belongs_to :type
  belongs_to :statut
  
  has_many :facture_items
  has_many :produits, :through => :facture_items
  
  def total_htva
    facture_items.to_a.sum { |facture_item| facture_item.total_htva }
  end
  
  def total_tva
    facture_items.to_a.sum { |facture_item| facture_item.total_tva }
  end
  
  def produits_list
    produits.map { |p| p.nom }.join(", ")
  end
end

app/models/facture_item.rb
class FactureItem < ActiveRecord::Base
  attr_accessible :descritpion, :libelle, :prix, :quantite, :tva_id, :produit_id
  
  belongs_to :facture
  belongs_to :produit
  belongs_to :tva
  
  def total_htva
    prix * quantite
  end
  
  def total_tva
    tva_value = Tva.find(tva_id)
    tva_taux = 1.0 + (tva_value.value.to_f / 100)
    total_htva * tva_taux
  end
end

app/models/produit.rb
class Produit < ActiveRecord::Base
  attr_accessible :nom, :quantite, :reference, :prix
  
  has_many :facture_items
  has_many :factures, :through => :facture_items
end

app/models/statut.rb
class Statut < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/tva.rb
class Tva < ActiveRecord::Base
  attr_accessible :display, :libelle, :value
  
  has_many :facture_item
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :display, :libelle
  
  has_many :factures
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :login, :mail, :hashed_password, :salt, :password_confirmation, :password
  has_many :factures
  
  validates :login, :presence => true, :uniqueness => true
  
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  
  validate :password_must_be_present
  
  after_destroy :ensure_an_user_remains 
  
  def User.authenticate(login, password)
    if user = find_by_login(login)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "security" + salt)
  end
  
  # 'password' = attribut virtuel
  def password=(password)
    @password = password
   
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private
    def password_must_be_present
      errors.add(:password, 'Missing password') unless hashed_password.present?
    end
  
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def ensure_an_user_remains
    if User.count.zero?
      raise "Can't delete last user!"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_factures = Facture.count
  end
end

app/controllers/factures_controller.rb
class FacturesController < ApplicationController
  # GET /factures
  # GET /factures.json
  def index
    @factures = Facture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factures }
    end
  end

  # GET /factures/1
  # GET /factures/1.json
  def show
    @facture = Facture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @facture }
    end
  end

  # GET /factures/new
  # GET /factures/new.json
  def new
    @facture = Facture.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @facture }
    end
  end

  # GET /factures/1/edit
  def edit
    @facture = Facture.find(params[:id])
  end

  # POST /factures
  # POST /factures.json
  def create
    params[:facture][:user_id] = session[:user_id]
    @facture = Facture.new(params[:facture])

    respond_to do |format|
      if @facture.save
        format.html { redirect_to @facture, notice: 'Facture was successfully created.' }
        format.json { render json: @facture, status: :created, location: @facture }
      else
        format.html { render action: "new" }
        format.json { render json: @facture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factures/1
  # PUT /factures/1.json
  def update
    @facture = Facture.find(params[:id])

    respond_to do |format|
      if @facture.update_attributes(params[:facture])
        format.html { redirect_to @facture, notice: 'Facture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @facture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factures/1
  # DELETE /factures/1.json
  def destroy
    @facture = Facture.find(params[:id])
    @facture.destroy

    respond_to do |format|
      format.html { redirect_to factures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize
  
  def index
  end
end

app/controllers/tvas_controller.rb
class TvasController < ApplicationController
  # GET /tvas
  # GET /tvas.json
  def index
    @tvas = Tva.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tvas }
    end
  end

  # GET /tvas/1
  # GET /tvas/1.json
  def show
    @tva = Tva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tva }
    end
  end

  # GET /tvas/new
  # GET /tvas/new.json
  def new
    @tva = Tva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tva }
    end
  end

  # GET /tvas/1/edit
  def edit
    @tva = Tva.find(params[:id])
  end

  # POST /tvas
  # POST /tvas.json
  def create
    @tva = Tva.new(params[:tva])

    respond_to do |format|
      if @tva.save
        format.html { redirect_to @tva, notice: 'Tva was successfully created.' }
        format.json { render json: @tva, status: :created, location: @tva }
      else
        format.html { render action: "new" }
        format.json { render json: @tva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tvas/1
  # PUT /tvas/1.json
  def update
    @tva = Tva.find(params[:id])

    respond_to do |format|
      if @tva.update_attributes(params[:tva])
        format.html { redirect_to @tva, notice: 'Tva was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tvas/1
  # DELETE /tvas/1.json
  def destroy
    @tva = Tva.find(params[:id])
    @tva.destroy

    respond_to do |format|
      format.html { redirect_to tvas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuts_helper.rb
module StatutsHelper
end

app/helpers/tvas_helper.rb
module TvasHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/factures/_form.html.erb
<%= form_for(@facture) do |f| %>
  <% if @facture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facture.errors.count, "error") %> prohibited this facture from being saved:</h2>

      <ul>
      <% @facture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :intitule %><br />
    <%= f.text_field :intitule %>
  </div>
  <div>
	<%= f.label :client_id %><br />
    <%= collection_select(:facture, :client_id, Client.all, :id, :societe) %>
  </div>
  <div class="field">
    <%= f.label :statut_id %><br />
    <%= collection_select(:facture, :statut_id, Statut.all, :id, :libelle) %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= collection_select(:facture, :type_id, Type.all, :id, :libelle) %>
  </div>
  <div class="field">
    <%= f.label :date_facturation %><br />
    <%= f.date_select :date_facturation, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :delai_paiement %><br />
    <%= f.number_field :delai_paiement, :min => 0, :max => 75, :value => 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factures/edit.html.erb
<h1>Editing facture</h1>

<%= render 'form' %>

<%= link_to 'Show', @facture %> |
<%= link_to 'Back', factures_path %>

app/views/factures/index.html.erb
<h1>Listing factures</h1>

<table>
  <tr>
    <th>Reference</th>
    <th>Societe</th>
    <th>Intitule</th>
    <th>Date facturation</th>
	<th>Statut</th>
	<th>Produits</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @factures.each do |facture| %>
  <tr>
    <td><%= facture.reference %></td>
	<td><%= facture.client.societe %></td>
    <td><%= facture.intitule %></td>
    <td><%= facture.date_facturation %></td>
    <td><%= facture.statut.libelle %></td>
	<td><%= facture.produits_list %></td>
    <td><%= link_to 'Show', facture %></td>
    <td><%= link_to 'Edit', edit_facture_path(facture) %></td>
    <td><%= link_to 'Destroy', facture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Facture', new_facture_path %>

app/views/factures/new.html.erb
<h1>New facture</h1>

<%= render 'form' %>

<%= link_to 'Back', factures_path %>

app/views/factures/show.html.erb
<p>
  <b>User:</b>
  <%= @facture.user.login %>
</p>

<p>
  <b>Reference:</b>
  <%= @facture.reference %>
</p>

<p>
  <b>Intitule:</b>
  <%= @facture.intitule %>
</p>

<p>
  <b>Date facturation:</b>
  <%= @facture.date_facturation %>
</p>

<p>
  <b>Delai paiement:</b>
  <%= @facture.delai_paiement %>
</p>

<p>
  <b>Client:</b>
  <%= @facture.client.societe %>
</p>

<p>
  <b>Type:</b>
  <%= @facture.type.libelle %>
</p>

<p>
  <b>Statut:</b>
  <%= @facture.statut.libelle %>
</p>

<p>
  <b>Total:</b>
  <%= number_to_currency(@facture.total_tva, :unit => "€") %>
</p>

<h2>Items</h2>
<table>
  <tr>
    <th>Libelle</th>
    <th>Quantite</th>
    <th>Prix unitaire</th>
	<th>Tva</th>
	<th>Total</th>
    <th>Descritpion</th>
    <th></th>
    <th></th>
  </tr>
<% @facture.facture_items.each do |facture_item| %>
  <tr>
    <td><%= facture_item.libelle %></td>
    <td><%= facture_item.quantite %></td>
    <td><%= number_to_currency(facture_item.prix, :unit => "€") %></td>
	<td><%= facture_item.tva.libelle %></td>
    <td><%= number_to_currency(facture_item.total_tva, :unit => "€") %></td>
	<td><%= facture_item.descritpion %></td>
    <td><%= link_to 'Edit', edit_facture_item_path(facture_item.id) %></td>
    <td><%= link_to 'Destroy', [@facture, facture_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<h2>Add an item:</h2>
<%= form_for([@facture, @facture.facture_items.build]) do |f| %>
  <div class="field">
    <%= f.label :libelle %><br />
    <%= f.text_field :libelle %>
  </div>
  <div class="field">
	<%= f.label :produit_id %><br />
	<%= collection_select(:facture_item, :produit_id, Produit.all, :id, :nom) %>
  </div>
  <div class="field">
	<%= f.label :tva_id %><br />
	<%= collection_select(:facture_item, :tva_id, Tva.all, :id, :libelle) %>
  </div>
  <div class="field">
    <%= f.label :quantite %><br />
    <%= f.number_field :quantite, :min => 0, :max => 9999, :value => 1 %>
  </div>
  <div class="field">
    <%= f.label :descritpion %><br />
    <%= f.text_area :descritpion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_facture_path(@facture) %> |
<%= link_to 'Back', factures_path %>